/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../pages/token_view/sol_token_view.dart';
import '../pages/token_view/token_view.dart';
import '../pages/wallet_view/wallet_view.dart';
import '../pages_desktop_specific/my_stack_view/wallet_view/desktop_sol_token_view.dart';
import '../pages_desktop_specific/my_stack_view/wallet_view/desktop_token_view.dart';
import '../pages_desktop_specific/my_stack_view/wallet_view/desktop_wallet_view.dart';
import '../providers/providers.dart';
import '../utilities/constants.dart';
import '../utilities/open_wallet.dart';
import '../utilities/util.dart';
import '../wallets/wallet/impl/sub_wallets/solana_token_wallet.dart';
import 'conditional_parent.dart';
import 'rounded_white_container.dart';
import 'wallet_info_row/wallet_info_row.dart';

class SimpleWalletCard extends ConsumerWidget {
  const SimpleWalletCard({
    super.key,
    required this.walletId,
    this.contractAddress,
    this.popPrevious = false,
    this.desktopNavigatorState,
  });

  final String walletId;
  final String? contractAddress;
  final bool popPrevious;
  final NavigatorState? desktopNavigatorState;

  void _openWallet(BuildContext context, WidgetRef ref) async {
    final nav = Navigator.of(context);
    // This card may be popped below.
    final read = ProviderScope.containerOf(context).read;
    final wallet = ref.read(pWallets).getWallet(walletId);
    if (!await openWallet(context, ref, wallet)) return;
    if (popPrevious) nav.pop();

    final contractAddress = this.contractAddress;
    if (contractAddress == null) {
      if (desktopNavigatorState != null) {
        unawaited(
          desktopNavigatorState!.pushNamed(
            DesktopWalletView.routeName,
            arguments: walletId,
          ),
        );
      } else {
        unawaited(nav.pushNamed(WalletView.routeName, arguments: walletId));
      }
      return;
    }

    final tokenWallet = await loadTokenWallet(
      desktopNavigatorState?.context ?? context,
      read,
      wallet,
      contractAddress,
    );
    if (tokenWallet == null) return;
    setCurrentTokenWallet(read, tokenWallet);
    final isSolana = tokenWallet is SolanaTokenWallet;
    if (desktopNavigatorState != null) {
      await desktopNavigatorState!.pushNamed(
        isSolana ? DesktopSolTokenView.routeName : DesktopTokenView.routeName,
        arguments: walletId,
      );
    } else {
      await nav.pushNamed(
        isSolana ? SolTokenView.routeName : TokenView.routeName,
        arguments: (walletId: walletId, popPrevious: !Util.isDesktop),
      );
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ConditionalParent(
      condition: !Util.isDesktop,
      builder: (child) => RoundedWhiteContainer(
        padding: const EdgeInsets.all(0),
        child: MaterialButton(
          // splashColor: Theme.of(context).extension<StackColors>()!.highlight,
          key: Key("walletsSheetItemButtonKey_$walletId"),
          padding: const EdgeInsets.all(10),
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              Constants.size.circularBorderRadius,
            ),
          ),
          onPressed: () => _openWallet(context, ref),
          child: child,
        ),
      ),
      child: WalletInfoRow(
        walletId: walletId,
        contractAddress: contractAddress,
        onPressedDesktop: Util.isDesktop
            ? () => _openWallet(context, ref)
            : null,
      ),
    );
  }
}
