/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:opencryptopay/opencryptopay.dart';

import '../../models/isar/models/contract.dart';
import '../../networking/http.dart';
import '../../notifications/show_flush_bar.dart';
import '../../providers/ui/preview_tx_button_state_provider.dart';
import '../../utilities/amount/amount.dart';
import '../../utilities/amount/amount_formatter.dart';
import '../../utilities/logger.dart';
import '../../utilities/show_loading.dart';
import '../../utilities/text_styles.dart';
import '../../utilities/util.dart';
import '../../wallets/crypto_currency/crypto_currency.dart';
import '../../widgets/desktop/desktop_dialog.dart';
import '../../widgets/desktop/primary_button.dart';
import '../../widgets/stack_dialog.dart';

/// Bridges Stack Wallet's [CryptoCurrency] to opencryptopay package's
/// [CryptoCoin] interface.
class CryptoCurrencyAdapter implements CryptoCoin {
  CryptoCurrencyAdapter(
    this.currency, {
    this.tokenSymbol,
  });

  final CryptoCurrency currency;

  /// When set (for EVM/Solana token wallets), overrides [ticker] with the
  /// token's symbol so the OpenCryptoPay `asset` request parameter targets
  /// the token (e.g. "USDT") instead of the chain's native coin (e.g. "ETH").
  final String? tokenSymbol;

  @override
  String get ticker => tokenSymbol ?? currency.ticker;

  @override
  String get prettyName => currency.prettyName;

  @override
  String get displayName => tokenSymbol ?? currency.prettyName;
}

class OpenCryptoPaySendHandler {
  OpenCryptoPaySendHandler({
    required this.ref,
    required this.coin,
    required this.sendToController,
    required this.cryptoAmountController,
    required this.setValidAddress,
    required this.isMounted,
    this.tokenContract,
  });

  final WidgetRef ref;
  final CryptoCurrency coin;
  final TextEditingController sendToController;
  final TextEditingController cryptoAmountController;
  final void Function(String address) setValidAddress;
  final bool Function() isMounted;

  final Contract? tokenContract;

  int get _fractionDigits =>
      tokenContract?.decimals ?? coin.fractionDigits;

  final OpenCryptoPayController _controller = OpenCryptoPayController(
    service: OpenCryptoPayService(client: StackClient()),
  );
  OpenCryptoPayTransactionDetails? _details;
  String? _method;

  Future<OpenCryptoPayResult?> _run({
    required BuildContext context,
    required String qrData,
    required CryptoCoin coin,
    required String logLabel,
  }) async {
    return showLoading<OpenCryptoPayResult>(
      whileFuture: _controller.run(
        qrData: qrData,
        coin: coin,
        onError: (e, s) =>
            Logging.instance.w(logLabel, error: e, stackTrace: s),
      ),
      context: context,
      rootNavigator: Util.isDesktop,
      message: OpenCryptoPayStrings.loading,
    );
  }

  Future<OpenCryptoPaySuccess?> _showErrorOrSuccess(
    BuildContext context,
    OpenCryptoPayResult result,
  ) async {
    switch (result) {
      case OpenCryptoPayNoPending():
        await _showError(
          context: context,
          title: OpenCryptoPayStrings.noPendingTitle,
          message: OpenCryptoPayStrings.noPendingMessage,
        );
      case OpenCryptoPayUnsupported():
        await _showError(
          context: context,
          title: OpenCryptoPayStrings.unsupportedMethodTitle,
          message: OpenCryptoPayStrings.unsupportedMethod,
        );
      case OpenCryptoPayLightning():
        await _showError(
          context: context,
          title: OpenCryptoPayStrings.lightningTitle,
          message: OpenCryptoPayStrings.lightningMessage,
        );
      case OpenCryptoPayInvalidAddress():
        await _showError(
          context: context,
          title: OpenCryptoPayStrings.invalidAddressTitle,
          message: OpenCryptoPayStrings.invalidAddressMessage,
        );
      case OpenCryptoPayError(:final title, :final message):
        await _showError(context: context, title: title, message: message);
      case OpenCryptoPaySuccess():
        return result;
    }
    return null;
  }

  /// Decode a scanned OpenCryptoPay link, fetch the pending payment details
  /// for this wallet's coin, and prefill the send form in place.
  Future<void> handle(BuildContext context, String qrData) async {
    final result = await _run(
      context: context,
      qrData: qrData,
      coin: CryptoCurrencyAdapter(coin, tokenSymbol: tokenContract?.symbol),
      logLabel: "OpenCryptoPay flow failed",
    );

    if (!isMounted() || result == null) return;

    // ignore: use_build_context_synchronously
    final success = await _showErrorOrSuccess(context, result);
    if (success != null) _applySuccess(success);
  }

  void _applySuccess(OpenCryptoPaySuccess result) {
    _details = result.details;
    _method = result.method;

    // Prefill the form in place.
    final address = result.address;
    sendToController.text = address;

    final amount = result.amount;
    if (amount != null) {
      final parsed = result.isRawAmount
          ? Amount(
              rawValue: BigInt.tryParse(amount.toString()) ?? BigInt.zero,
              fractionDigits: _fractionDigits,
            )
          : amount.toAmount(fractionDigits: _fractionDigits);
      cryptoAmountController.text = ref
          .read(pAmountFormatter(coin))
          .format(parsed, withUnitName: false);
      ref.read(pSendAmount.notifier).state = parsed;
    }

    setValidAddress(address);
  }

  /// Submit proof of payment (tx hash) to the OpenCryptoPay provider for the
  /// active OpenCryptoPay payment. On failure the pending proof reference is
  /// retained so the caller can retry; it is only cleared on success.
  Future<void> submitProof(BuildContext context, String txid) async {
    final details = _details;
    final method = _method;
    if (details == null || method == null) return;
    try {
      final error = await _controller.submitProof(
        details: details,
        method: method,
        txHash: txid,
      );
      if (error == null) {
        // Success: clear the pending proof reference.
        _details = null;
        _method = null;
        return;
      }
      Logging.instance.w(
        "OpenCryptoPay proof submission failed",
        error: error,
      );
      if (!isMounted()) return;
      unawaited(
        showFloatingFlushBar(
          type: FlushBarType.warning,
          message: OpenCryptoPayStrings.proofFailed(error),
          // ignore: use_build_context_synchronously
          context: context,
        ),
      );
    } catch (e, s) {
      // Keep _details/_method so the caller can retry.
      Logging.instance.w(
        "OpenCryptoPay proof submission threw",
        error: e,
        stackTrace: s,
      );
      if (!isMounted()) return;
      unawaited(
        showFloatingFlushBar(
          type: FlushBarType.warning,
          message: OpenCryptoPayStrings.proofFailed(e),
          // ignore: use_build_context_synchronously
          context: context,
        ),
      );
    }
  }

  Future<void> _showError({
    required BuildContext context,
    required String title,
    required String message,
  }) async {
    if (!isMounted()) return;
    await showDialog<void>(
      context: context,
      builder: (context) {
        if (Util.isDesktop) {
          return DesktopDialog(
            maxWidth: 450,
            child: Padding(
              padding: const EdgeInsets.all(32),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(title, style: STextStyles.desktopH3(context)),
                  const SizedBox(height: 24),
                  Text(
                    message,
                    style: STextStyles.desktopTextSmall(context),
                  ),
                  const SizedBox(height: 56),
                  Row(
                    children: [
                      const Spacer(),
                      Expanded(
                        child: PrimaryButton(
                          buttonHeight: ButtonHeight.l,
                          label: "Ok",
                          onPressed: Navigator.of(context).pop,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          );
        }
        return StackOkDialog(title: title, message: message);
      },
    );
  }
}
