/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:opencryptopay/opencryptopay.dart';

import '../../networking/http.dart';
import '../../utilities/amount/amount.dart';
import '../../utilities/enums/fee_rate_type_enum.dart';
import '../../utilities/extensions/extensions.dart';
import '../../utilities/logger.dart';
import '../../utilities/show_loading.dart';
import '../../utilities/util.dart';
import '../../wallets/crypto_currency/crypto_currency.dart';
import '../../wallets/wallet/wallet.dart';
import '../../widgets/desktop/primary_button.dart';
import '../../widgets/desktop/secondary_button.dart';
import '../../widgets/dialogs/basic_dialog.dart';
import '../../widgets/eth_fee_form.dart';
import '../../widgets/stack_dialog.dart';
import 'open_crypto_pay_send_fee.dart';
import 'open_crypto_pay_switch_wallet.dart';
import 'open_crypto_pay_switch_wallet_dialog.dart';

({String title, String message}) _quoteMismatchText({
  required bool sameRecipient,
  required bool sameAmount,
}) {
  final changed = switch ((sameRecipient, sameAmount)) {
    (false, false) => "recipient and amount",
    (false, true) => "recipient",
    _ => "amount",
  };
  return (
    title: "${changed.capitalize()} changed",
    message:
        "The payment request asked for a different $changed. "
        "The seller may not recognize this payment.",
  );
}

/// Map a wallet [CryptoCurrency] (plus optional token symbol) to the
/// library's [CryptoCoin] descriptor.
CryptoCoin cryptoCoinFor(CryptoCurrency currency, {String? tokenSymbol}) =>
    CryptoCoin(
      ticker: tokenSymbol ?? currency.ticker,
      prettyName: currency.prettyName,
      displayName: tokenSymbol ?? currency.prettyName,
    );

typedef BusinessDetail = ({String label, String value, Uri? uri});

/// Opens the send view of [candidate] with [payment] prefilled.
typedef OpenCryptoPaySwitchWallet = Future<void> Function(
  BuildContext context,
  OpenCryptoPayCandidate candidate,
  OpenCryptoPaySuccess payment,
);

const _tokenMismatchTitle = "Different token";
const _pickedTokenMismatchMessage =
    "The payment request is for a token with a different contract address "
    "than the chosen token.";
const _tokenMismatchMessage =
    "The payment request is for a token with a different contract address "
    "than this wallet's token. Scan the code from the wallet holding that "
    "token.";

class OpenCryptoPaySendHandler {
  OpenCryptoPaySendHandler({
    required this.coin,
    required this.sendToController,
    required this.onAmountReceived,
    required this.setValidAddress,
    this.tokenSymbol,
    this.tokenDecimals,
    this.tokenContractAddress,
    this.candidates,
    this.switchWallet,
    @visibleForTesting OpenCryptoPayController? controller,
  }) : _controller =
           controller ??
           OpenCryptoPayController(
             service: OpenCryptoPayService(client: StackClient()),
           );

  final CryptoCurrency coin;
  final TextEditingController sendToController;
  final void Function(Amount amount) onAmountReceived;
  final void Function(String address) setValidAddress;

  /// Set for token wallets (ERC-20, SPL, ...) so the OpenCryptoPay request
  /// targets the token asset (ex: "USDT") instead of the chain's native coin
  /// and amounts use the token's decimals.
  final String? tokenSymbol;
  final int? tokenDecimals;

  /// Set for token wallets; a request for another contract is refused.
  final String? tokenContractAddress;

  /// The wallets and tokens offered when the provider rejects [coin]; read
  /// at that moment only.
  final List<OpenCryptoPayCandidate> Function()? candidates;
  final OpenCryptoPaySwitchWallet? switchWallet;

  int get _fractionDigits => tokenDecimals ?? coin.fractionDigits;

  final OpenCryptoPayController _controller;
  OpenCryptoPaySession? _session;
  Amount? _quotedAmount;
  bool _quoteOverridden = false;

  /// Whether the user chose to send despite a recipient or amount that
  /// differs from the payment request.
  bool get quoteOverridden => _quoteOverridden;

  void reset() {
    _session = null;
    _quotedAmount = null;
    _quoteOverridden = false;
  }

  Future<void> showQuoteExpiredError(
    BuildContext context, {
    bool paymentNotSent = false,
  }) => _showError(
    context: context,
    title: OpenCryptoPayStrings.quoteExpiredTitle,
    message: OpenCryptoPayStrings.quoteExpiredMessage(
      paymentNotSent: paymentNotSent,
    ),
  );

  bool get requiresBroadcast => _session?.requiresBroadcast ?? true;

  bool get isQuoteExpired => _session?.isQuoteExpired ?? false;

  List<BusinessDetail> get businessDetails {
    final details = _session?.details;
    if (details == null) return const [];
    final recipient = details.recipient;
    BusinessDetail? detail(String label, String? value, {Uri? uri}) =>
        value == null || value.isEmpty
        ? null
        : (label: label, value: value, uri: uri);
    final legalName = details.legalName;
    return [
      legalName == null
          ? detail("Name", details.displayName)
          : detail("Legal name", legalName),
      if (recipient != null) ...[
        detail("Postal address", recipient.postalAddress),
        detail("Phone number", recipient.phone, uri: recipient.phoneUri),
        detail("Email", recipient.mail, uri: recipient.mailUri),
        detail("Website", recipient.website, uri: recipient.websiteUri),
        detail("Registration number", recipient.registrationNumber),
      ],
    ].nonNulls.toList();
  }

  bool isActivePaymentFor(String? recipientAddress) =>
      _session?.isActivePaymentFor(recipientAddress) ?? false;

  /// Whether sending [amount] to [address] may proceed. A pending payment
  /// request with another recipient or amount asks for confirmation.
  Future<bool> confirmSend(
    BuildContext context,
    String? address,
    Amount amount,
  ) async {
    final session = _session;
    if (session == null || session.isCompleted || session.isQuoteExpired) {
      return true;
    }
    final sameRecipient = session.isActivePaymentFor(address);
    final sameAmount = _quotedAmount == null || amount == _quotedAmount;
    if (sameRecipient && sameAmount) return true;
    if (!context.mounted) return false;
    final text = _quoteMismatchText(
      sameRecipient: sameRecipient,
      sameAmount: sameAmount,
    );
    final proceed = await _confirm(context, text.title, text.message);
    if (proceed) _quoteOverridden = true;
    return proceed;
  }

  /// The fee to build the transaction with: the given one, raised to the
  /// payment request's minimum when below it. Null when the send must stop.
  /// [feeRateApplies] is false when the send builds its own fee.
  Future<OpenCryptoPaySendFee?> sendFee(
    BuildContext context,
    Wallet wallet, {
    required String? address,
    required Amount amount,
    required FeeRateType feeRateType,
    int? satsPerVByte,
    EthEIP1559Fee? ethFee,
    bool feeRateApplies = true,
  }) async {
    final chosen = (
      feeRateType: feeRateType,
      satsPerVByte: satsPerVByte,
      ethFee: ethFee,
    );
    final session = _session;
    if (!feeRateApplies ||
        session == null ||
        session.minFee <= 0 ||
        !session.isActivePaymentFor(address)) {
      return chosen;
    }
    return openCryptoPaySendFee(
      context,
      wallet,
      amount: amount,
      minFee: session.minFee,
      chosen: chosen,
      confirm: _confirm,
      unmet: (context, title, message) =>
          _showError(context: context, title: title, message: message),
    );
  }

  Future<bool> _confirm(
    BuildContext context,
    String title,
    String message,
  ) async {
    final proceed = await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (context) => BasicDialog(
        title: title,
        message: message,
        leftButton: SecondaryButton(
          label: "Cancel",
          onPressed: () => Navigator.of(context).pop(false),
        ),
        rightButton: PrimaryButton(
          label: "Continue",
          onPressed: () => Navigator.of(context).pop(true),
        ),
        flex: true,
      ),
    );
    return proceed ?? false;
  }

  Future<void> _showError({
    required BuildContext context,
    required String title,
    required String message,
  }) async {
    if (!context.mounted) return;
    await showDialog<void>(
      context: context,
      builder: (_) => StackOkDialog(
        title: title,
        message: message,
        desktopPopRootNavigator: Util.isDesktop,
        maxWidth: Util.isDesktop ? 600 : null,
      ),
    );
  }

  Future<void> handle(BuildContext context, String qrData) async {
    // The library iterates ownedCoins only when it rejects the coin.
    List<OpenCryptoPayCandidate>? candidates;
    Iterable<CryptoCoin> ownedCoins() sync* {
      candidates ??= this.candidates?.call() ?? const [];
      yield* candidates!.map((c) => c.coin);
    }

    final result = await _resolve(
      context,
      qrData,
      cryptoCoinFor(coin, tokenSymbol: tokenSymbol),
      ownedCoins: ownedCoins(),
    );
    if (!context.mounted) return;

    if (result case OpenCryptoPayUnsupported(:final alternatives?)
        when alternatives.isNotEmpty) {
      return _offerSwitch(context, qrData, _payable(candidates!, alternatives));
    }
    return handleResult(context, result);
  }

  /// Runs the payment flow for [coin] under a loading dialog.
  Future<OpenCryptoPayResult?> _resolve(
    BuildContext context,
    String qrData,
    CryptoCoin coin, {
    Iterable<CryptoCoin>? ownedCoins,
  }) => showLoading<OpenCryptoPayResult>(
    whileFuture: _controller.run(
      qrData: qrData,
      coin: coin,
      ownedCoins: ownedCoins,
      onError: (e, s) => Logging.instance.w(
        "OpenCryptoPay flow failed",
        error: e,
        stackTrace: s,
      ),
    ),
    context: context,
    rootNavigator: Util.isDesktop,
    message: OpenCryptoPayStrings.loading,
  );

  /// Prefills the form from [result], or shows its error.
  Future<void> handleResult(
    BuildContext context,
    OpenCryptoPayResult? result,
  ) async {
    switch (result) {
      case null:
        await _showError(
          context: context,
          title: OpenCryptoPayStrings.genericErrorTitle,
          message: OpenCryptoPayStrings.genericErrorMessage,
        );
      case OpenCryptoPayFailure():
        final text = OpenCryptoPayStrings.failure(result);
        await _showError(
          context: context,
          title: text.title,
          message: text.message,
        );
      case OpenCryptoPaySuccess() when result.session.isQuoteExpired:
        await showQuoteExpiredError(context);
      case OpenCryptoPaySuccess() when _isOtherToken(result):
        await _showError(
          context: context,
          title: _tokenMismatchTitle,
          message: _tokenMismatchMessage,
        );
      case OpenCryptoPaySuccess():
        _applySuccess(result);
    }
  }

  /// Candidates the provider accepts for this payment.
  static List<OpenCryptoPayCandidate> _payable(
    List<OpenCryptoPayCandidate> candidates,
    List<CryptoCoin> alternatives,
  ) => candidates
      .where(
        (c) => alternatives.any(
          (a) => a.prettyName == c.coin.prettyName && a.ticker == c.coin.ticker,
        ),
      )
      .toList();

  /// Lets the user pick one of [payable] to pay with, resolves the payment
  /// for it and hands both to [switchWallet].
  Future<void> _offerSwitch(
    BuildContext context,
    String qrData,
    List<OpenCryptoPayCandidate> payable,
  ) async {
    final switchWallet = this.switchWallet;
    if (payable.isEmpty || switchWallet == null) {
      final text = OpenCryptoPayStrings.failure(
        const OpenCryptoPayUnsupported(),
      );
      return _showError(
        context: context,
        title: text.title,
        message: text.message,
      );
    }
    final chosen = await showDialog<OpenCryptoPayCandidate>(
      context: context,
      builder: (_) => OpenCryptoPaySwitchWalletDialog(
        ticker: tokenSymbol ?? coin.ticker,
        candidates: payable,
      ),
    );
    if (chosen == null || !context.mounted) return;
    final payment = await _resolve(context, qrData, chosen.coin);
    if (!context.mounted) return;
    if (payment is! OpenCryptoPaySuccess) return handleResult(context, payment);
    if (payment.session.isQuoteExpired) return showQuoteExpiredError(context);
    if (_otherContract(payment, chosen.contractAddress)) {
      return _showError(
        context: context,
        title: _tokenMismatchTitle,
        message: _pickedTokenMismatchMessage,
      );
    }
    await switchWallet(context, chosen, payment);
  }

  bool _isOtherToken(OpenCryptoPaySuccess result) =>
      _otherContract(result, tokenContractAddress);

  /// Whether [result] names a token contract other than [held].
  static bool _otherContract(OpenCryptoPaySuccess result, String? held) {
    final requested = result.tokenContractAddress;
    return requested != null &&
        held != null &&
        requested.toLowerCase() != held.toLowerCase();
  }

  void _applySuccess(OpenCryptoPaySuccess result) {
    _session = result.session;

    // Prefill the form in place.
    final address = result.address;
    sendToController.text = address;

    final rawAmount = result.amountInSmallestUnit(_fractionDigits);
    final quoted = rawAmount == null
        ? null
        : Amount(rawValue: rawAmount, fractionDigits: _fractionDigits);
    _quotedAmount = quoted;
    _quoteOverridden = false;
    if (quoted != null) onAmountReceived(quoted);

    setValidAddress(address);
  }

  Future<bool> submitProof(BuildContext context, String txProof) async {
    final session = _session;
    if (session == null) return true;

    final result = await session.submitProof(txProof);
    switch (result) {
      case OpenCryptoPayProofAccepted():
        _session = null;
        return true;
      case OpenCryptoPayProofQuoteExpired(:final error):
        Logging.instance.w(
          "OpenCryptoPay proof submission failed",
          error: error,
        );
        if (!context.mounted) return false;
        await showQuoteExpiredError(context, paymentNotSent: true);
        return false;
      case OpenCryptoPayProofFailed(:final error, :final providerAnswered):
        Logging.instance.w(
          "OpenCryptoPay proof submission failed",
          error: error,
        );
        if (!context.mounted) return false;
        final text = OpenCryptoPayStrings.proofFailure(
          requiresBroadcast: session.requiresBroadcast,
          providerAnswered: providerAnswered,
        );
        await _showError(
          context: context,
          title: text.title,
          message: text.message,
        );
        return false;
    }
  }
}
