/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:opencryptopay/opencryptopay.dart';

import '../../themes/coin_icon_provider.dart';
import '../../themes/stack_colors.dart';
import '../../utilities/text_styles.dart';
import '../../utilities/util.dart';
import '../../widgets/icon_widgets/eth_token_icon.dart';
import '../../widgets/rounded_white_container.dart';
import 'open_crypto_pay_send_handler.dart';

class OpenCryptoPaySupportedCoins extends ConsumerWidget {
  const OpenCryptoPaySupportedCoins({
    super.key,
    required this.coin,
    required this.alternatives,
    required this.onSwitch,
  });

  final CryptoCoin coin;

  final List<CryptoCoin> alternatives;

  final void Function(CryptoCoin coin) onSwitch;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final stackColors = Theme.of(context).extension<StackColors>()!;
    final isDesktop = Util.isDesktop;

    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Row(
          children: [
            Icon(
              Icons.info_outline,
              color: stackColors.accentColorOrange,
              size: isDesktop ? 24 : 22,
            ),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                "${coin.displayName} is not supported",
                style: isDesktop
                    ? STextStyles.desktopH3(context)
                    : STextStyles.titleBold12(context),
              ),
            ),
          ],
        ),
        const SizedBox(height: 8),
        Text(
          alternatives.isEmpty
              ? "This seller does not accept ${coin.displayName}, and none of "
                  "your other wallets use a supported coin."
              : "This seller does not accept ${coin.displayName}. You can pay "
                  "with one of your other wallets instead:",
          style: isDesktop
              ? STextStyles.desktopTextExtraExtraSmall(context).copyWith(
                  fontSize: 18,
                )
              : STextStyles.itemSubtitle12(context),
        ),
        if (alternatives.isNotEmpty) ...[
          SizedBox(height: isDesktop ? 20 : 16),
          ...alternatives.map(
            (alt) => Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: isDesktop
                  ? _DesktopAlternativeRow(alt: alt, onSwitch: onSwitch)
                  : _MobileAlternativeRow(alt: alt, onSwitch: onSwitch),
            ),
          ),
        ],
      ],
    );
  }
}

class _MobileAlternativeRow extends ConsumerWidget {
  const _MobileAlternativeRow({required this.alt, required this.onSwitch});

  final CryptoCoin alt;
  final void Function(CryptoCoin coin) onSwitch;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return RoundedWhiteContainer(
      child: InkWell(
        onTap: () => onSwitch(alt),
        child: Row(
          children: [
            _AlternativeIcon(coin: alt, size: 24),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                alt.displayName,
                style: STextStyles.titleBold12(context),
              ),
            ),
            Text("PAY", style: STextStyles.link2(context)),
          ],
        ),
      ),
    );
  }
}

class _DesktopAlternativeRow extends ConsumerWidget {
  const _DesktopAlternativeRow({required this.alt, required this.onSwitch});

  final CryptoCoin alt;
  final void Function(CryptoCoin coin) onSwitch;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return RoundedWhiteContainer(
      padding: const EdgeInsets.all(16),
      borderColor: Theme.of(context).extension<StackColors>()!.background,
      hoverColor:
          Theme.of(context).extension<StackColors>()!.buttonBackSecondary,
      onPressed: () => onSwitch(alt),
      child: Row(
        children: [
          _AlternativeIcon(coin: alt, size: 28),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              alt.displayName,
              style: STextStyles.desktopTextExtraSmall(context),
            ),
          ),
          Text(
            "SELECT",
            style: STextStyles.desktopTextExtraExtraSmall(
              context,
            ).copyWith(
              color: Theme.of(context)
                  .extension<StackColors>()!
                  .accentColorBlue,
            ),
          ),
        ],
      ),
    );
  }
}

/// Shows the correct icon for an alternative coin: [EthTokenIcon] for
/// ERC-20 tokens (by contract address), or the native coin icon otherwise.
class _AlternativeIcon extends ConsumerWidget {
  const _AlternativeIcon({required this.coin, required this.size});

  final CryptoCoin coin;
  final double size;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final adapter = coin as CryptoCurrencyAdapter;
    if (adapter.tokenContractAddress != null) {
      return EthTokenIcon(
        contractAddress: adapter.tokenContractAddress!,
        size: size,
      );
    }
    return SvgPicture.file(
      File(ref.watch(coinIconProvider(adapter.currency))),
      width: size,
      height: size,
    );
  }
}
