/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:opencryptopay/opencryptopay.dart';

/// Carries a pending OpenCryptoPay payment from one wallet's send view to
/// another's when the user switches to an alternative wallet. The sender
/// (the wallet that discovered the unsupported-coin state) writes the success
/// here before navigating; the receiver reads and clears it in initState so
/// it can restore the proof-of-payment reference and prefill the form.
///
/// Shared by mobile and desktop send views.
final openCryptoPayPrefillProvider =
    StateProvider<OpenCryptoPaySuccess?>((ref) => null);
