#should deny
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare repository
        uses: actions/checkout@v4
      - name: Install Flutter 
        uses: subosito/flutter-action@v2 
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: install dependencies
        run: |
          cargo install cargo-ndk
          rustup target add x86_64-unknown-linux-gnu
          sudo apt clean
          sudo apt update
          sudo apt install -y unzip automake build-essential file pkg-config git python libtool libtinfo5 cmake openjdk-8-jre-headless libgit2-dev clang libncurses5-dev libncursesw5-dev zlib1g-dev llvm debhelper libclang-dev opencl-headers libssl-dev ocl-icd-opencl-dev libc6-dev-i386 cmake ninja-build pkg-config libgtk-3-dev liblzma-dev meson python3-pip libgirepository1.0-dev valac xsltproc docbook-xsl
          pip3 install --upgrade meson==0.64.1 markdown==3.4.1 markupsafe==2.1.1 jinja2==3.1.2 pygments==2.13.0 toml==0.10.2 typogrify==2.0.7 tomli==2.0.1
      - name: Build secure storage
        run: |
          cd scripts/linux
          ./build_secure_storage_deps.sh
      - name: Build secp256k1
        run: |
           cd scripts/linux
           ./build_secp256k1.sh
      - name: Prebuild
        run: |
          cd scripts
          ./prebuild.sh
      - name: Build App
        run: |
          rustup install 1.67.1-x86_64-unknown-linux-gnu
          rustup install 1.71.0-x86_64-unknown-linux-gnu
          rustup install 1.72.0-x86_64-unknown-linux-gnu
          cd scripts
          ./build_app.sh -a stack_wallet -p linux -v 2.1.9 -b staging <<END_SCRIPT
           yes
           END_SCRIPT
      - name: Get Flutter dependencies
        run: |
          flutter pub get
      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Test
        run: |
          flutter test --coverage
